workflows:
  ios-workflow:
    name: Zuryo iOS Build
    max_build_duration: 60
    environment:
      groups:
        - app_store_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.zuryotech.app
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods
        script: |
          cd $CM_BUILD_DIR
          pod install
      - name: Build iOS
        script: |
          xcode-project use-profiles
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/Zuryo.xcworkspace" \
            --scheme "Zuryo"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
